eureka:
  client:
    enabled: false
spring:
  application:
    name: apizza-order
  datasource:
    driver-class-name: org.postgresql.Driver
    username: 'user'
    password: 'pass'
    url: 'jdbc:postgresql://localhost:5432/apizza_order_db'
  kafka:
    bootstrap-servers: localhost:29092
  jwt:
    jwks-url: 'http://localhost:5555/.well-known/jwks'